### ISSUE TITLE
[REFACTOR] 1차 리팩토링 (modify & fix)

### ISSUE THREAD

**Issue by haydenCho** [IT-Cotato/9th-Growing-Pain-FE#105]
# 🛠️ Description for refactoring features
작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [ ] 지원현황 컴포넌트 다시 구성
- [ ] 응원메세지 기능
- [x] 마이페이지 경력, 나에 대해서 → 인풋 필드 말고 메모 필드로 수정
- [x] 커뮤니티 활동-저장한 글 → 삭제 대신 저장 취소
- [ ] 지원현황 알림 디데이
- [x] 활동기록 생성 시 성과 및 활동 내용 저장되도록 수정 -> 백엔드에서 수정해줌!
