### ISSUE TITLE
[REFACTOR] 1차 리팩토링

### ISSUE THREAD

**Issue by vcz-polly** [IT-Cotato/9th-Growing-Pain-FE#107]
# 🛠️ Description for refactoring features
작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [ ] 댓글 좋아요 목록 get 요청 필요(멤버별 아이디를 파라미터로)
- **CommentModal.jsx 코드 구조 분리**
    - [x]  댓글 작성: CommentForm
    - [x]  본문: PostText
    - [x]  댓글 목록: CommentList, CommentItem 
   
- [ ]  댓글 개수 연동
- [x] 좋아요 처리
- [x]  대댓글 기능 오류 수정
- [ ]  커뮤니티 스크롤 그 안에서만 되게(사이드바 고정)
