### ISSUE TITLE
[FEAT] 성장기록, 지원현황, 활동기록 페이지 UI

### ISSUE THREAD

**Issue by haydenCho** [IT-Cotato/9th-Growing-Pain-FE#13]
## 🛠️ Description for development features
성장기록, 지원현황, 활동기록 페이지 구현

## 📝 Todo-lists
- [x] 성장기록 페이지 구현
- [x] 지원현황 페이지 구현
    - [x] 편집 컴포넌트 UI 구현
        - [x] 기록 페이지에서 사용
        - [x] 상세(편집) 페이지에서 사용
- [x] 활동기록 페이지 구현
    - [x] 편집 컴포넌트 구현
        - [x] 기록 페이지에서 사용
        - [x] 상세(편집) 페이지에서 사용
