### ISSUE TITLE
[FIX] 성장기록 및 지원현황 문제점 수정

### ISSUE THREAD

**Issue by haydenCho** [IT-Cotato/9th-Growing-Pain-FE#44]
## 🛠️ Description for development features
성장기록 및 지원현황 문제점 수정

## 📝 Todo-lists
- [x]  지원현황 키 에러 해결
- [x]  지원현황 아이템 같은 데이터는 같이 렌더링
- [x]  성장기록: 지원현황 마감한 지원은 렌더링 X
