### ISSUE TITLE
[FEAT] 지원현황 수정

### ISSUE THREAD

**Issue by haydenCho** [IT-Cotato/9th-Growing-Pain-FE#56]
## 🛠️ Description for development features
지원현황 수정 및 기능 연결

## 📝 Todo-lists
- [x] 리스트 조회 페이지(대쉬보드, 성장기록, 지원현황) 임시 데이터 변환
- [x] 지원현황 페이지 삭제 기능
- (후순위) 피드백 페이지 UI -> 1차 리팩토링(#104)에서 관리
- [x] (후순위) 편집 컴포넌트 토글 내용 저장
