### ISSUE TITLE
[FEAT] 마이페이지 기능 연동

### ISSUE THREAD

**Issue by haydenCho** [IT-Cotato/9th-Growing-Pain-FE#79]
## 🛠️ Description for development features
마이페이지 기능 연동

## 📝 Todo-lists
- 기본 정보
    - [x] 멤버 정보 조회
    - [x] 기본 정보 수정
    - [x] 추가 정보 등록
    - [ ] (후순위)프로필 공개 여부 설정

- 커뮤니티 활동
    - [x] 내 활동 조회
    - [x] 내 활동 삭제

- 계정관리
    - [x] 비밀번호 수정
    - [x] 분야 수정

- 알림
    - [x] 댓글 알림
    - [x] 지원현황 D-1, 3, 7 안내
